### ISSUE TITLE
Intercom

### ISSUE THREAD

**Issue by abidlabs** [abidlabs/zakat.fyi#14]
Plugin to allow real-time chat
(see mockup)

**Comment by itinawi** [comment]
They have multiple tiers that we can use. Here's a (layout)[https://www.intercom.com/pricing] of the pricing.

Right now, the `Grow` tier seems to be the one that makes the most sense for us. 

It costs $99/month, but I applied as an early stage company, which will give us a free trial of 14 days followed by a reduced fee of $49/month for the first year.

I placed my card information on the application, and it will not be charged until the trial period ends.

**Comment by itinawi** [comment]
I added the body of code required to install Intercom to all the .html pages.

Since we will not have logged-in users, all you need to copy-paste into the html code is the following

`    <script>
      window.intercomSettings = {
        app_id: "zifidfn5"
      };
    </script>

    <script>
    // We pre-filled your app ID in the widget URL: 'https://widget.intercom.io/widget/zifidfn5'
    (function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',w.intercomSettings);}else{var d=document;var i=function(){i.c(arguments);};i.q=[];i.c=function(args){i.q.push(args);};w.Intercom=i;var l=function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/zifidfn5';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);};if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();
    </script>`
